### ISSUE TITLE
error installing to windows machine

### ISSUE THREAD

**Issue by aronlmin** [Fauntleroy/react-simple-dropdown#27]
doesnt work without es2016 as a preset

```
ERROR in ./~/react-simple-dropdown/lib/components/Dropdown.js
Module build failed: Error: Couldn't find preset "es2016" relative to directory "C:\\Users\\ALilland\\Documents\\macros\\experiments\\mongoid\\mongoid_heroku\\db_core_app\\node_modules\\react-simple-dropdown"
    at C:\Users\ALilland\Documents\macros\experiments\mongoid\mongoid_heroku\db_core_app\node_modules\babel-core\lib\transformation\file\options\option-manager.js:299:19
    at Array.map (native)
    at OptionManager.resolvePresets (C:\Users\ALilland\Documents\macros\experiments\mongoid\mongoid_heroku\db_core_app\node_modules\babel-core\lib\transformation\file\options\option-manager.js:270:20)
    at OptionManager.mergePresets (C:\Users\ALilland\Documents\macros\experiments\mongoid\mongoid_heroku\db_core_app\node_modules\babel-core\lib\transformation\file\options\option-manager.js:259:10)
    at OptionManager.mergeOptions (C:\Users\ALilland\Documents\macros\experiments\mongoid\mongoid_heroku\db_core_app\node_modules\babel-core\lib\transformation\file\options\option-manager.js:244:14)
    at OptionManager.init (C:\Users\ALilland\Documents\macros\experiments\mongoid\mongoid_heroku\db_core_app\node_modules\babel-core\lib\transformation\file\options\option-manager.js:374:12)
    at File.initOptions (C:\Users\ALilland\Documents\macros\experiments\mongoid\mongoid_heroku\db_core_app\node_modules\babel-core\lib\transformation\file\index.js:216:65)
    at new File (C:\Users\ALilland\Documents\macros\experiments\mongoid\mongoid_heroku\db_core_app\node_modules\babel-core\lib\transformation\file\index.js:139:24)
    at Pipeline.transform (C:\Users\ALilland\Documents\macros\experiments\mongoid\mongoid_heroku\db_core_app\node_modules\babel-core\lib\transformation\pipeline.js:46:16)
    at transpile (C:\Users\ALilland\Documents\macros\experiments\mongoid\mongoid_heroku\db_core_app\node_modules\babel-loader\lib\index.js:38:20)
    at Object.module.exports (C:\Users\ALilland\Documents\macros\experiments\mongoid\mongoid_heroku\db_core_app\node_modules\babel-loader\lib\index.js:133:12)
 @ ./src/components/Navbar.jsx 13:27-59
```

when installing es2016 errors occur:

```
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\ALilland\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save-dev" "es2016"
npm ERR! node v6.3.1
npm ERR! npm  v4.0.5

npm ERR! Cannot convert undefined or null to object
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\ALilland\Documents\macros\experiments\mongoid\mongoid_heroku\db_core_app\npm-debug.log
```

**Comment by Fauntleroy** [comment]
What command causes this error to occur? Are you using browserify & babel to compile a bundle?

Off the top of my head this sounds like it might be an issue related to top level browserify/babel configurations accidentally being applied to all imported modules.
